### ISSUE TITLE
Knowing when spinner is being shown

### ISSUE THREAD

**Issue by tamitutor** [Chevtek/angular-spinners#11]
Ok, another question...The spinner does not easily center align because it is a span.  SO I've embedded it in a div but now the div is taking space regardless of if the spinner is shown or hidden...So can we either change the spinner to be a div (easier to align--see this [SO](http://stackoverflow.com/questions/8392211/html-span-align-center-not-working)) or somehow get the current state of the spinner (show).

**Comment by AlexAllocated** [comment]
I went ahead and changed the container element to a `div`. Remove whatever hack you did and grab the latest, then let me know if that fixes the issue. It _shouldn't_ be taking up space if not shown and I'm hoping that the reason it was is due to a side-effect of whatever hack you supplied. Try out the latest version (3.0.2) and let me know.

**Comment by tamitutor** [comment]
It's working great!  Thanks!

**Comment by AlexAllocated** [comment]
:+1:
