### ISSUE TITLE
Spinner and grunt uglyfy/usemin

### ISSUE THREAD

**Issue by Stwissel** [Chevtek/angular-spinners#12]
As part of my workflow I use a grunt script that deploys to dist by all sorts of steps including concatenation and minification. Spinners work brilliant in the uncompressed version, but won't show up after Grunt has a go.
What do I miss in my approach?

[Gruntfile.js.txt](https://github.com/codetunnel/angular-spinners/files/33202/Gruntfile.js.txt)

**Comment by AlexAllocated** [comment]
This is not your fault. I apologize for not getting to this sooner. The reason is that in my naivety I did not include string versions of dependencies in my library because I personally use an angular minifier that does it for me. This being a third party library though means I should probably be doing that so it can be minified safely without the use of that specific utility. I'll update when I have a new version for you shortly.

**Comment by AlexAllocated** [comment]
Alright. v3.1.2 is now published and should be minified without issues. Please let me know if you encounter any more problems.
