### ISSUE TITLE
Type definitions file for angular-spinners

### ISSUE THREAD

**Issue by ShirlyA** [Chevtek/angular-spinners#17]
where can I find an angular-spinners.d.ts file for your lib?

**Comment by AlexAllocated** [comment]
I'm not familiar enough with Typescript at the moment but I will take some time this week and educate myself so I can provide you what you need. Thanks.

**Comment by AlexAllocated** [comment]
The old version of this library would not have supported Typescript very well. Between when this issue was posted and now I have educated myself on both Typescript and Angular2+ pretty thoroughly. Version 5 and higher of angular-spinners drops support for Angular 1 and now supports Angular 2 and higher. It is also complete with type definitions and is packaged as UMD and ready to go with SystemJS if desired 😃
