### ISSUE TITLE
Don't include any additional markup when img is not set.

### ISSUE THREAD

**Issue by mchiareli** [Chevtek/angular-spinners#18]
Currently even when image is not set a img and an additional div is placed inside the spinner markup, is possible to get ride of them?

May cause bugs in layouts.

**Comment by AlexAllocated** [comment]
This is now changed in v3.1.1. The `img` tag is now using an `ng-if` instead of `ng-show` so the markup is omitted entirely without an image source. Also, the `<div ng-transclude></div>` has been changed to `<ng-transclude></ng-transclude>` in the hopes that the entire element will then be replaced with the transcluded content.
