### ISSUE TITLE
A Spinner with the name 'x' has already been registered.

### ISSUE THREAD

**Issue by aaroncmoore** [Chevtek/angular-spinners#7]
I've run into this issue when navigating through my site.  Since I don't have the spinner registration on the Index, if the user navigates to the url where the spinner is registered this error is thrown.  I'd like to request an option to register a spinner if it doesn't exist or check for an already registered spinner.

**Comment by gxedwards** [comment]
I have the same issue when I have the spinner html  in a partial.

**Comment by AlexAllocated** [comment]
When this happens it is usually in partials and single page apps. Try to find the relevant area of your app where the original spinner should be unregistered with the spinner service, so that it can re-register again later. You can call `spinnerService._unregister('spinner name')` to remove a spinner from the service.

**Comment by AlexAllocated** [comment]
If this does not solve it for you, your app structure may be a tad redundant. I'd be happy to take a look if you have a link to the source you can share :)

**Comment by superyonjan** [comment]
Well in my case, I had kept it inside repeat directive. Make sure you did not did the same
 
    <div ng-repeat="n in [1, 2, 3]">
        <spinner name="x" show="true"></spinner>
    </div>

**Comment by AlexAllocated** [comment]
Closing this for now. Let me know if there's anything else I can do to help.
